### PR TITLE
v1.4.0 (CosmWasm v1)

### PR DESCRIPTION
**Pull request by assafmo**
- [x] In `ContractInstance`/`start_engine()`, check whether the wasm is v0.10 or v1 ([using this export](https://github.com/CosmWasm/cosmwasm/blob/v0.16/packages/vm/README.md#compatibility)) and store it in `ContractInstance`, then (after the crypto stuff) according to the cosmwasm version, initialize the `env` object that is given to the contract in:
  - [x]  [`init`](https://github.com/enigmampc/SecretNetwork/blob/c05c74f9eddc6213515a39dd43c7446b08e3cea8/cosmwasm/packages/wasmi-runtime/src/wasm/contract_operations.rs#L103)
  - [x] [`handle`](https://github.com/enigmampc/SecretNetwork/blob/c05c74f9eddc6213515a39dd43c7446b08e3cea8/cosmwasm/packages/wasmi-runtime/src/wasm/contract_operations.rs#L221)
  - [x] [`query`](https://github.com/enigmampc/SecretNetwork/blob/c05c74f9eddc6213515a39dd43c7446b08e3cea8/cosmwasm/packages/wasmi-runtime/src/wasm/contract_operations.rs#L300) (in v1 `query` has `env` too).
    - [x] Pass `env` from Go to `query`. 
    - [x] In `query`, don't need to pass `contract_key` prefixed to `msg` anymore, because it's also inside `env`.
- [x] Also, invoke the right wasm function:
  - [x] v0.10 `init` or v1 `instantiate` ([link](https://github.com/enigmampc/SecretNetwork/blob/c05c74f9eddc6213515a39dd43c7446b08e3cea8/cosmwasm/packages/wasmi-runtime/src/wasm/runtime/engine.rs?plain=1#L40)).
  - [x] v0.10 `handle` or v1 `execute` ([link](https://github.com/enigmampc/SecretNetwork/blob/c05c74f9eddc6213515a39dd43c7446b08e3cea8/cosmwasm/packages/wasmi-runtime/src/wasm/runtime/engine.rs?plain=1#L106))
- [x] Afterwards, translate the v1 output into v0.10 output so that the Go code will handle it nicely.
  - [x] Add `plaintext_log()` to cosmwasm-std v1
  - [x] Handle v1 `submessages`. TODO: See how cosmwasm implemented this, we might want to piggyback off `messages` and handle it in the Go code, or maybe we can handle it right there inside the enclave by converting them to normal messages.   
- [x] Fix wasm validation. The new v1 API needs [these](https://github.com/CosmWasm/cosmwasm/blob/c14937849cedf7c70f85c15b90053bdcf01e8a1c/packages/vm/src/compatibility.rs?plain=1#L12-L41) while we currently have the v0.10 API which validates [these](https://github.com/enigmampc/SecretNetwork/blob/c05c74f9eddc6213515a39dd43c7446b08e3cea8/cosmwasm/packages/sgx-vm/src/compatability.rs?plain=1#L11-L34). In order to support both in parallel, we need to fix the validation code.
- [x] Implement new v1 API
  - [x] `db_read` - we already have this from v0.10
  - [x] `db_write` - we already have this from v0.10
  - [x] `db_remove` - we already have this from v0.10
  - [x] `addr_validate`
  - [x] `addr_canonicalize` - need to alias from `canonicalize_address` (v0.10)
  - [x] `addr_humanize` - need to alias from `humanize_address` (v0.10)
  - [x] `secp256k1_verify`
  - [x] `secp256k1_recover_pubkey`
  - [x] `ed25519_verify`
  - [x] `ed25519_batch_verify`
  - [x] `ed25519_sign` - we've added on top on v1
  - [x] `secp256k1_sign` - we've added on top on v1 
  - [x] `debug` - debug prints from inside the contract
  - [x] `query_chain` - we already have this from v0.10
  - [x] Charge gas for all functions that don't go back into the chain (Basically the `addr` & `crypto` ones).
- [x] New contract entry points
  - [x] `ibc_channel_open()`
  - [x] `ibc_channel_connect()`
  - [x] `ibc_channel_close()`
  - [x] `ibc_packet_receive()`
  - [x] `ibc_packet_ack()`
  - [x] `ibc_packet_timeout()`
  - [x] `reply()`
- [x] Implement migration for `cotnractInfo` due to the new changes (added IBC port for each contract)
- [x] When handling submessages of v0.10, make sure that errors when `ReplyOn::Never` fails the tx (because in v0.10 errors on submessages always failed the tx) - Code-Wise we saw that the behavior is as expected but a test need to be written
- [x] Add `Withdraw` handler to v1 `StakingMsg` 
- [x] Handler `callback_sig` for v1 result inside the enclave 
- [x] Audit StargateQuery's whitelist
- [x] Audit StargateMsg
- [x] Test the `data` field - v1 lets replies override the data field, while v0.10 always returns the first message's data field.
- [x] Initialize `Env.TransactionInfo`

### CODE REVIEW

**Comment by faddat** [comment]
So, I did this

https://github.com/scrtlabs/cosmos-sdk/pull/167

https://github.com/CosmWasm/wasmd/pull/863

and

https://github.com/cosmos/ibc-go/pull/1653

but depends on if ya'd like to get freaky or nah I suppose?

:P 

downside: grpc only
upside: grpc only
upside: mempool prioritization

**Comment by assafmo** [comment]
> So, I did this
> 
> * [Scrt 46 cosmos-sdk#167](https://github.com/scrtlabs/cosmos-sdk/pull/167)
> * [Cosmos SDK v46 CosmWasm/wasmd#863](https://github.com/CosmWasm/wasmd/pull/863)
> 
> and
> 
> * [cosmos sdk 46 upgrade cosmos/ibc-go#1653](https://github.com/cosmos/ibc-go/pull/1653)
> 
> but depends on if ya'd like to get freaky or nah I suppose?
> 
> :P
> 
> downside: grpc only upside: grpc only upside: mempool prioritization

We do want it, also has gov and authz goodies. But first we just need to check with all exchanges that they're not using the old REST API.

**Comment by assafmo** [comment]
But yeah please base new work on the cosmwasm-v1 branch ❤️

**Comment by faddat** [comment]
About the API, I think that these breaking changes are worth exploring because I think others will have similar concerns. It is my understanding that the GRPC gateway could get us around this but I don't know how accurate that is.

**Comment by assafmo** [comment]
> It is my understanding that the GRPC gateway could get us around this but I don't know how accurate that is.

Yes that's accurate.

**Comment by faddat** [comment]
OK, so basically -- if we're fundamentally good with "we won't break exchange API's if go to 46" -- I'd like to either invite you guys to the Notional slack server, or to a call or something.

We're doing 46 on numerous chains and I'd love for secret to be one of them.

**Comment by assafmo** [comment]
> OK, so basically -- if we're fundamentally good with "we won't break exchange API's if go to 46" -- I'd like to either invite you guys to the Notional slack server, or to a call or something.
> 
> We're doing 46 on numerous chains and I'd love for secret to be one of them.

We'd love to open a Slack connect! Our Slack org name is `enigmaco`.

We're still reaching out to exchanges and we'll know for sure in a few weeks. Our next chain upgrade is planned for September, so there's some time before we need to make a decision re 45->46.

Cc @YonatanE22

**Comment by assafmo** [comment]
# How to test an upgrade with LocalSecret

## Step 1

Start a v1.3 chain. Port 9091 open for secret.js tests.

```bash
docker run -it -p 9091:9091 --name localsecret ghcr.io/scrtlabs/localsecret:v1.3.1
```

## Step 2

Run secret.js tests, to create state on the chain before the upgrade.

First delete globalSetup & globalTeardown except for `waitForBlocks()` in globalSetup.

```bash
yarn test
```

## Step 3

Start a v1.4 chain just to extract the binaries from it.

```bash
docker run -it --rm --name localsecret-1.4 ghcr.io/scrtlabs/localsecret:v0.0.0
```

## Step 4

Copy binaries from v1.4 chain to v1.3 chain.

```bash
# Copy binaries from v1.4 chain to host (a limitation of `docker cp`)

rm -rf /tmp/upgrade-bin && mkdir -p /tmp/upgrade-bin

docker cp localsecret-1.4:/usr/bin/secretcli                                /tmp/upgrade-bin
docker cp localsecret-1.4:/usr/bin/secretd                                  /tmp/upgrade-bin
docker cp localsecret-1.4:/usr/lib/librust_cosmwasm_enclave.signed.so       /tmp/upgrade-bin
docker cp localsecret-1.4:/usr/lib/librust_cosmwasm_query_enclave.signed.so /tmp/upgrade-bin
docker cp localsecret-1.4:/usr/lib/libgo_cosmwasm.so                        /tmp/upgrade-bin

# Can kill localsecret-1.4 at this point
docker rm -f localsecret-1.4

# Copy binaries from host to current v1.3 chain

docker exec localsecret bash -c 'rm -rf /tmp/upgrade-bin && mkdir -p /tmp/upgrade-bin'

docker cp /tmp/upgrade-bin/secretcli                                localsecret:/tmp/upgrade-bin
docker cp /tmp/upgrade-bin/secretd                                  localsecret:/tmp/upgrade-bin
docker cp /tmp/upgrade-bin/librust_cosmwasm_enclave.signed.so       localsecret:/tmp/upgrade-bin
docker cp /tmp/upgrade-bin/librust_cosmwasm_query_enclave.signed.so localsecret:/tmp/upgrade-bin
docker cp /tmp/upgrade-bin/libgo_cosmwasm.so                        localsecret:/tmp/upgrade-bin

# Overwrite v1.3 binaries with v1.4 binaries without affecting file permissions
# v1.3 chain is still running at this point
# we assume v1.3 binaries are loaded to RAM
# so overwriting them with v1.4 binraies won't take effect until a process restart

docker exec localsecret bash -c 'cat /tmp/upgrade-bin/secretcli                                > /usr/bin/secretcli'
docker exec localsecret bash -c 'cat /tmp/upgrade-bin/librust_cosmwasm_enclave.signed.so       > /usr/lib/librust_cosmwasm_enclave.signed.so'
docker exec localsecret bash -c 'cat /tmp/upgrade-bin/librust_cosmwasm_query_enclave.signed.so > /usr/lib/librust_cosmwasm_query_enclave.signed.so'
docker exec localsecret bash -c 'cat /tmp/upgrade-bin/libgo_cosmwasm.so                        > /usr/lib/libgo_cosmwasm.so'

# We cannot overwrite secretd because it's being used ("Text file busy")
# so instead we're going to point the init script to the new binary

# don't setup secretcli
docker exec localsecret bash -c $'perl -i -pe \'s/^.*?secretcli.*$//\' bootstrap_init.sh'

# point script to the v1.4 secretd file
docker exec localsecret bash -c $'perl -i -pe \'s;RUST_BACKTRACE=1 secretd start;RUST_BACKTRACE=1 /tmp/upgrade-bin/secretd start;\' bootstrap_init.sh'
```

## Step 5

Propose a software upgrade on v1.3 chain.

```bash
# 40 blocks (4 minutes) until upgrade block
UPGRADE_BLOCK="$(docker exec localsecret bash -c 'secretcli status | jq "(.SyncInfo.latest_block_height | tonumber) + 40"')"

# Propose upgrade
PROPOSAL_ID="$(docker exec localsecret bash -c "secretcli tx gov submit-proposal software-upgrade v1.4 --upgrade-height $UPGRADE_BLOCK --title 'Shockwave Delta Upgrade' --description YOLO --deposit 100000000uscrt --from a -y -b block | jq '.logs[0].events[] | select(.type == \"submit_proposal\") | .attributes[] | select(.key == \"proposal_id\") | .value | tonumber'")"

# Vote yes (voting period is 90 seconds)
docker exec localsecret bash -c "secretcli tx gov vote $PROPOSAL_ID yes --from a -y -b block"
```

# Step 6

Apply the upgrade.

Wait until you see `ERR CONSENSUS FAILURE!!! err="UPGRADE \"v1.4\" NEEDED at height` in the logs, then run:

```bash
docker stop localsecret
docker start localsecret -a
```

You should see `INF applying upgrade "v1.4" at height` in the logs, following by blocks continute to stream.

# Step 7

Test that old v0.10 contracts are still working (query + exec + init from stored code)

# Step 8

Run the integration tests from `SecretNetwork/integration-tests`, without IBC:

```diff
- describe("IBC", () => {
+ describe.skip("IBC", () => {
```

```bash
yarn test
```

**Review by liorbond — DISMISSED** [review]

**Review by Cashmaney — APPROVED** [review]

**Pull request merged**
