### PR TITLE
Add secret args to build enclave test image

### PR DESCRIPTION
**Pull request by sbellem**

### CODE REVIEW

**Comment by Cashmaney** [comment]
Ty for this. We're going to be reworking all the different dockerfiles shortly, but this is appreciated in the interim

**Comment by sbellem** [comment]
> Ty for this. We're going to be reworking all the different dockerfiles shortly, but this is appreciated in the interim

You're welcome! Totally new to this codebase, and trying to understand how to run tests locally, to be able to experiment with the code.

**Comment by Cashmaney** [comment]
Sure thing. Let us know if you have any questions, or if there's anything unclear (which I'm sure there is - we change things way more than we update the docs 😅)

**Comment by sbellem** [comment]
One thing I wonder is whether the `SPID` and `API_KEY` are really necessary to run the enclave tests. Looking at the [`ci.yml`](https://github.com/scrtlabs/SecretNetwork/blob/a38fa73a5af6558a0c27091a23f3b55d962bcdb5/.github/workflows/ci.yaml#L6) under `.github`, it looks like they are not.

**Comment by sbellem** [comment]
Also, I guess you are re-working this, but the base image (`baiduxlab/sgx-rust:2004-1.1.3`) used for the [enclave-test.Dockerfile](https://github.com/scrtlabs/SecretNetwork/blob/a38fa73a5af6558a0c27091a23f3b55d962bcdb5/deployment/dockerfiles/enclave-test.Dockerfile#L1) is somewhat outdated  If I am not mistaken, it is using the SGX SDK 2.12 as per their [Dockerfile](https://hub.docker.com/layers/baiduxlab/sgx-rust/2004-1.1.3/images/sha256-247247599026ef2e74e8f793211d96f23341c7a357ef509835bdcffe9eff0b3a?context=explore) on DockerHub. 

If you wish, I could make a PR for a Dockerfile which uses the 2.17 SDK like you do in `ci.yml`. (I already have the Dockerfile for personal use.)

**Pull request merged**
