### PR TITLE
Port dev image faucet from python to node #957

### PR DESCRIPTION
**Pull request by levackt**
Please see if this is what you had in mind, if it's not already being handled anyway.

### CODE REVIEW

**Comment by Cashmaney** [comment]
Awesome, this will be useful:)

Can you also remove the Python install from the docker image, and undraft this? I went ahead and changed the target branch so we can merge it into a feature branch and have the CI run properly before merging to master

**Comment by levackt** [comment]
Great, although I thought I already [removed Python here](https://github.com/scrtlabs/SecretNetwork/pull/959/commits/e17104d3a3975c0517fc1a2c4a5a9c0d3b7a9b5f#diff-a2a21b032013783c17a5f80a166f80a385cd138c27ee1698311404a74553fea8)

Undrafting and checking for anywhere else

**Comment by Cashmaney** [comment]
> Great, although I thought I already [removed Python here](https://github.com/scrtlabs/SecretNetwork/pull/959/commits/e17104d3a3975c0517fc1a2c4a5a9c0d3b7a9b5f#diff-a2a21b032013783c17a5f80a166f80a385cd138c27ee1698311404a74553fea8)
> 
> Undrafting and checking for anywhere else

Oh yeah, missed that!

**Comment by assafmo** [comment]
Do we have tests that use the faucet API?
@levackt can you use `setsid` instead of `nohup` ([it's more reliable](https://www.ibm.com/support/pages/nohup-or-setsid-keep-process-running-after-user-disconnect))?

**Comment by levackt** [comment]
> Do we have tests that use the faucet API? @levackt can you use `setsid` instead of `nohup` ([it's more reliable](https://www.ibm.com/support/pages/nohup-or-setsid-keep-process-running-after-user-disconnect))?

No problem, testing with setsid

**Pull request merged**
