### PR TITLE
rocksdb & mod cleanup

### PR DESCRIPTION
**Pull request by faddat**
This is for:

* relay performance
* go.mod legibility
* sync performance
* re-enablement of rocksdb

Fact is that rocksdb will give you much, much better performance while all of us work on the deeper issues keeping cosmos chains from performing how they should.

We are still looking for hardware to validate.

Much love,

-Jacob﻿

### CODE REVIEW

**Comment by Cashmaney** [comment]
Thanks @faddat! I'm going to leave this PR open till we have time to integrate it and test together with the rest of our performance-related changes. Testing various databases is pretty time-consuming, so being able to share the love from the ecosystem is super helpful. Thanks for the PR!

**Comment by dylanschultzie** [comment]
@Cashmaney can you build a linux binary of this for me? I've been going through the motions for it, but it's a winding staircase of dependency hell I find.

**Comment by dylanschultzie** [comment]
@Cashmaney can you compile this for me? I can create the cli, but struggling to get a full release so I can run start with it.

**Comment by Cashmaney** [comment]
@dylanschultzie building this here: https://github.com/scrtlabs/SecretNetwork/actions/runs/1674241240
And continuing to track the issue here: https://github.com/scrtlabs/SecretNetwork/pull/871

**Comment by faddat** [comment]
@dylanschultzie has provided me with the needed machine and I'm going to run through the compile steps and I'll post them here.  Seems like you guys mostly ubuntu?

**Comment by dylanschultzie** [comment]
@faddat yeah that's correct, afaik everyone does. 20.04, specifically

**Pull request merged**
