### PR TITLE
Custom chain ID from env

### PR DESCRIPTION
**Pull request by levackt**
CHAINID via env var doesn't work, it's always secretdev-1

### CODE REVIEW

**Comment by levackt** [comment]
The problem is the logic is inverted, so if the shorthand in the PR isn't preferred, we can fix it like so;
```sh

if [[ -z "${CHAINID}" ]]; then
    chain_id="secretdev-1"
else
    chain_id=$CHAINID
fi
```

**Comment by levackt** [comment]
Also present [here](https://github.com/scrtlabs/SecretNetwork/blob/88ccc92433ef3f5149226705e4a26a3c2ebc2279/deployment/docker/bootstrap/bootstrap_init.sh#L9), but probably only used by CI with defaults

**Comment by assafmo** [comment]
Cool, didn't know of this syntax.

**Comment by levackt** [comment]
Sure, let me check

**Comment by levackt** [comment]
Tests look better, squashed the commits and undrafting, should build

**Comment by Cashmaney** [comment]
LGTM! Thanks @levackt, merging this now

**Pull request merged**
